apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: redis-leader
  name: redis-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-leader
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: redis-leader
    spec:
      containers:
        - image: redis
          name: redis-leader
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
