apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: quay.io/kompose/web
          name: web
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
