apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: web-tcp
  name: web-tcp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: web
  type: LoadBalancer
